model: "ResNet"
sample_rate: &sample_rate 16000
dropout: &drop 0.0
repeat:  &rep  1
augment: true
lr_schedule: "PolynomialHoldDecayAnnealing"
lr_warmup_proportion: 0.1
kernel_size_factor: &kfactor 1.0


AudioAugmentor:
    shift:
        prob: 0.8
        min_shift_ms: -100.0
        max_shift_ms: 100.0
    noise:
        prob: 0.8

AudioToSpeechLabelDataLayer:
    train:
        shuffle: true
        num_workers: 0
    eval:
        num_workers: 0
        shuffle: false

AudioToMelSpectrogramPreprocessor:
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: &n_mels 64
    frame_splicing: 1
    dither: 0.00001
    stft_conv: true
    n_fft: 512

AudioToMFCCPreprocessor:
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    n_mels: *n_mels
    n_mfcc: *n_mels
    n_fft: 512
    

JasperEncoder:
    feat_in: *n_mels
    activation: "relu"
    conv_mask: true

    jasper:
        -   filters: 256
            repeat: 1
            kernel: [33]
            stride: [2]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [33]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [39]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [39]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [63]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [75]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 1
            kernel: [87]
            stride: [1]
            dilation: [2]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false

labels: ["the", "and", "of", "to", "a", "in", "he", "i", "that", "was", "it", "his", "with", "as", "for", "is", "had", "you", "her", "but", "not", "be", "she", "at", "on", "they", "by", "him", "this", "have", "which", "all", "from", "so", "said", "one", "my", "were", "me", "we", "or", "their", "are", "there", "when", "them", "no", "an", "if", "would", "who", "what", "will", "been", "out", "then", "up", "into", "could", "do", "more", "man", "now", "some", "very", "little", "time", "your", "upon", "about", "like", "than", "any", "only", "has", "two", "did", "its", "well", "other", "our", "over", "good", "before", "great", "after", "down", "made", "can", "see", "these", "should", "such", "old", "know", "came", "day", "must", "how", "never", "much", "us", "may", "come", "where", "mister", "first", "go", "way", "men", "long", "again", "himself", "went", "here", "back", "own", "most", "say", "even", "those", "without", "away", "might", "just", "think", "too", "make", "every", "through", "thought", "life", "am", "many", "still", "shall", "being", "take", "three", "eyes", "while", "same", "hand", "nothing", "found", "people", "place", "house", "last", "once", "yet", "saw", "off", "night", "don't", "let", "another", "put", "though", "get", "head", "took", "under", "things", "face", "young", "right", "ever", "tell", "new", "world", "thing", "room", "missus", "left", "looked", "asked", "always", "because", "look", "give", "sir", "mind", "work", "why", "seemed", "heard", "something", "years", "far", "going", "also", "father", "soon", "against", "each", "got", "king", "home", "find", "water", "few", "yes", "part", "told", "knew", "half", "mother", "side", "began", "having", "quite", "door", "called", "moment", "done", "better", "enough", "woman", "god", "whole", "love", "oh", "heart", "seen", "between", "both", "light", "course", "gave", "among", "hands", "turned", "almost", "days", "set", "however", "nor", "whom", "four", "until", "morning", "it's", "stood", "words", "small", "poor", "felt", "dear", "country", "hundred", "perhaps", "end", "white", "name", "miss", "does", "myself", "till", "lady", "anything", "brought", "girl", "together", "herself", "voice", "next", "best", "indeed", "themselves", "five", "since", "thus", "others", "feet", "matter", "round", "replied", "cannot", "large", "want", "rather", "looking", "i'm", "cried", "twenty", "taken", "word", "along", "nature", "boy", "kind", "high", "children", "full", "therefore", "whose", "gone", "power", "true", "air", "open", "lay", "behind", "sure", "sat", "wife", "death", "keep", "body", "near", "less", "fire", "alone", "believe", "passed", "lord", "given", "friend", "use", "rest", "sea", "often", "s", "money", "answered", "leave", "thousand", "present", "hope", "itself", "certain", "child", "black", "speak", "known", "city", "used", "help", "really", "state", "times", "earth", "i'll", "fact", "within", "least", "doctor", "above", "dead", "whether", "thou", "ground", "six", "hear", "general", "sent", "point", "means", "coming", "either", "reason", "order", "wish", "suddenly", "already", "women", "horse", "during", "case", "fell", "hard", "land", "son", "care", "held", "red", "returned", "lost", "around", "master", "became", "several", "making", "evening", "hour", "close", "second", "read", "everything", "dark", "question", "table", "friends", "form", "kept", "town", "manner", "beautiful", "possible", "towards", "become", "sight", "ten", "captain", "bed", "that's", "year", "big", "business", "mean", "o", "can't", "answer", "short", "arms", "war", "sometimes", "call", "sun", "family", "river", "says", "ready", "turn", "idea", "feel", "human", "different", "live", "ask", "else", "story", "followed", "truth", "carried", "across", "person", "fine", "prince", "able", "law", "sort", "letter", "ran", "rose", "doubt", "fear", "strange", "bring", "strong", "soul", "met", "reached", "happy", "cold", "sound", "understand", "john", "tree", "return", "past", "saying", "longer", "toward", "need", "taking", "didn't", "window", "suppose", "continued", "i've", "eye", "number", "deep", "road", "show", "appeared", "cut", "spoke", "daughter", "seven", "hold", "thee", "sense", "later", "clear", "talk", "hours", "opened", "free", "seems", "ought", "thy", "party", "brother", "tried", "pretty", "wanted", "certainly", "interest", "run", "hair", "lived", "none", "received", "cause", "common", "bad", "low", "beyond", "eighteen", "neither", "early", "although", "spirit", "subject", "real", "blood", "seem", "age", "feeling", "gold", "sleep", "husband", "street", "miles", "nearly", "entered", "won't", "account", "wind", "meet", "blue", "wild", "remember", "living", "public", "pleasure", "government", "church", "minutes", "further", "laid", "character", "heavy", "necessary", "except", "change", "green", "doing", "walked", "happened", "book", "eight", "forward", "line", "thirty", "glad", "try", "attention", "fellow", "led", "fall", "front", "late", "self", "fair", "caught", "knowledge", "seeing", "instead", "trees", "tom", "force", "purpose", "forth", "stand", "added", "fifty", "ship", "natural", "drew", "ye", "dream", "school", "english", "following", "arm", "grew", "view", "army", "thinking", "trouble", "standing", "thoughts", "silence", "ago", "effect", "foot", "stopped", "afraid", "act", "ill", "whatever", "there's", "food", "length", "beauty", "distance", "paper", "wall", "garden", "besides", "position", "eat", "england", "stone", "aunt", "yourself", "mine", "gentleman", "makes", "smile", "hardly", "sister", "princess", "exclaimed", "slowly", "dinner", "society", "queen", "uncle", "palace", "bright", "company", "mouth", "boys", "died", "art", "horses", "bear", "immediately", "desire", "wonder", "save", "girls", "fight", "third", "easy", "chance", "placed", "pass", "hall", "nine", "filled", "quickly", "saint", "comes", "action", "states", "french", "broken", "strength", "sweet", "walk", "top", "beside", "court", "getting", "single", "impossible", "piece", "stay", "loved", "sitting", "remained", "cat", "man's", "rich", "deal", "play", "follow", "struck", "according", "waiting", "opinion", "greater", "wait", "object", "he's", "started", "bird", "heaven", "chair", "probably", "arrived", "lips", "peace", "tears", "laughed", "wide", "ah", "dog", "pay", "sudden", "soft", "wood", "duty", "please", "simple", "speaking", "books", "de", "outside", "danger", "south", "experience", "clothes", "afternoon", "fast", "boat", "tone", "floor", "die", "chapter", "below", "straight", "island", "forest", "learned", "forty", "usual", "spring", "history", "dress", "latter", "field", "evil", "wrong", "send", "expected", "glass", "north", "presence", "hot", "giving", "corner", "merely", "months", "sky", "quiet", "born", "scarcely", "couldn't", "running", "leaving", "carry", "mary", "easily", "entirely", "talking", "stop", "direction", "appearance", "especially", "showed", "knows", "battle", "flowers", "secret", "morrow", "ladies", "cross", "watch", "wished", "raised", "joy", "twelve", "camp", "chief", "brown", "wise", "you're", "game", "killed", "london", "music", "finally", "bit", "service", "moved", "important", "count", "persons", "changed", "turning", "beginning", "mountain", "existence", "perfect", "fresh", "tea", "escape", "particular", "afterwards", "fortune", "places", "allowed", "rock", "condition", "office", "week", "closed", "golden", "meant", "moon", "animals", "happiness", "reach", "cry", "married", "conversation", "write", "plain", "understood", "figure", "anne", "wouldn't", "covered", "step", "respect", "silent", "visit", "lives", "trying", "ideas", "expression", "simply", "unless", "written", "shot", "box", "observed", "isn't", "terrible", "knight", "wonderful", "news", "circumstances", "middle", "discovered", "winter", "ears", "perfectly", "minute", "worth", "surprise", "iron", "threw", "spot", "add", "ancient", "thank", "silver", "future", "pleasant", "you'll", "legs", "animal", "lying", "american", "bread", "passing", "birds", "instant", "shook", "youth", "regard", "lie", "neck", "proper", "walls", "fish", "pain", "sit", "warm", "presently", "parts", "mere", "beneath", "built", "considered", "speech", "determined", "hill", "father's", "occasion", "note", "colonel", "steps", "laws", "heads", "broke", "greatest", "appear", "dropped", "creature", "wrote", "peter", "united", "faith", "leaves", "formed", "difficult", "surely", "darkness", "command", "west", "remain", "castle", "learn", "enemy", "various", "result", "degree", "space", "journey", "o'clock", "fifteen", "exactly", "paid", "spite", "grave", "begin", "snow", "drawn", "ways", "hat", "reply", "pale", "former", "houses", "likely", "dressed", "somewhat", "influence", "sharp", "goes", "carefully", "difficulty", "greatly", "bottom", "remembered", "sign", "believed", "lad", "serve", "marriage", "thick", "surface", "drawing", "forget", "hung", "holding", "train", "breath", "promise", "consider", "pleased", "board", "i'd", "tired", "letters", "touch", "sorry", "grown", "mountains", "property", "scene", "race", "fixed", "class", "shut", "watched", "tall", "president", "ourselves", "drink", "pieces", "shadow", "shore", "period", "madame", "lake", "summer", "notice", "decided", "altogether", "path"]