model: "QuartzNet"
sample_rate: &sample_rate 16000
dropout: &drop 0.0
repeat:  &rep  1
augment: true
lr_schedule: "PolynomialHoldDecayAnnealing"
lr_warmup_proportion: 0.1
kernel_size_factor: &kfactor 1.0

AudioAugmentor:
    shift:
        prob: 0.8
        min_shift_ms: -100.0
        max_shift_ms: 100.0
    noise:
        prob: 0.8
    resample:
        prob: 0.8

SpectrogramAugmentation:
    freq_masks: 2
    time_masks: 2
    freq_width: 15
    time_width: 25
    rect_masks: 5
    rect_time: 25
    rect_freq: 15


AudioToSpeechLabelDataLayer:
    #sample_rate: *sample_rate
    train:
        shuffle: true
        num_workers: 0
    eval:
        num_workers: 0
        shuffle: false

    
AudioToMelSpectrogramPreprocessor:
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: &n_mels 64
    frame_splicing: 1
    dither: 0.00001
    stft_conv: true
    n_fft: 512

AudioToMFCCPreprocessor:
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    n_mels: *n_mels
    n_mfcc: *n_mels
    n_fft: 512


JasperEncoder:
    feat_in: *n_mels
    activation: "relu"
    conv_mask: true

    jasper:
        -   filters: 256
            repeat: 1
            kernel: [33]
            stride: [2]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [33]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [39]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [39]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [63]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [75]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 1
            kernel: [87]
            stride: [1]
            dilation: [2]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false

JasperDecoderForClassification:
    return_logits: True
    pooling_type: 'avg'

labels: ['yes', 'no', 'up', 'down', 'left', 'right', 'on', 'off', 'stop', 'go', 'silence', 'other']
